import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const circe = localFont({
  src: [
    {
      path: "./fonts/CirceRounded-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/CirceRounded-ExtraLight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/CirceRounded-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/CirceRounded-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/CirceRounded-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/CirceRounded-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-circe-rounded",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${circe.className} antialiased   h-full`}
      >
        <div className="  bg-linear-to-b from-[#01EF92] to-[#00D8FB]">
          <NextIntlClientProvider messages={messages}>
            <div className="  box-border  ">{children}</div>
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
